apps/admin/config/routes.rb
Admin::Engine.routes.draw do
  scope "admin" do

    root to: 'home#index'
    get 'search/posts' => "home#post_search", as: 'post_search'
    get 'search/users' => "home#user_search", as: 'user_search'

    get  'login'  => 'login#new'
    post 'login'  => 'login#create'
    get  'logout' => 'login#destroy', as: 'logout'

    resources :users, only: [:show, :edit, :update] do
      member do
        get :posts
      end
    end

    resources :posts, only: [:show, :edit, :update]
  end
end

apps/admin/app/models/admin/post.rb
module Admin
  class Post < ::Content::Post

  end
end

apps/admin/app/models/admin/user.rb
module Admin
  class User < ::Account::User

  end
end

apps/admin/app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    layout 'admin/layouts/admin'
    include Shared::Controller::Manifests
    
    helper_method :current_user

    before_filter :require_admin_user

    def login!(user)
      session[:admin_user_id] = user.id
      redirect_to '/admin'
    end

    def logout!
      session.delete(:admin_user_id)
      redirect_to '/admin/login'
    end

    def current_user
      return @current_user if defined?(@current_user)
      @current_user = nil
      return nil unless session[:admin_user_id]
      @current_user = Admin::User.find_by_id(session[:admin_user_id])
    end

    # for layout
    helper_method :skip_sidebar
    def skip_sidebar
      @skip_sidebar = true
    end


    protected

    def require_admin_user
      redirect_to "/admin/login" and return unless current_user
      logout! unless current_user.admin?
    end

  end
end

apps/admin/app/controllers/admin/home_controller.rb
module Admin
  class HomeController < ::Admin::ApplicationController

    before_action :skip_sidebar
    
    def index
      @post_search = Admin::PostSearch.new
      @user_search = Admin::UserSearch.new
    end

    def post_search
      op = Admin::PostSearch.new(current_user)
      if op.submit(params)
        @results = op.results
        if @results.size == 1
           redirect_to @results.first
        end
      else
        redirect_to root_path, alert: 'No results found'
      end
    end

    def user_search
      op = Admin::UserSearch.new(current_user)
      if op.submit(params)
        @results = op.results
        if @results.size == 1
           redirect_to @results.first
        end
      else
        redirect_to root_path, alert: 'No results found'
      end
    end
  end
end

apps/admin/app/controllers/admin/login_controller.rb
module Admin
  class LoginController < ::Admin::ApplicationController
    helper Shared::Helper::Errors

    skip_before_filter :require_admin_user

    def new
      login!(current_user) and return if current_user
      @user = Admin::User.new
    end

    def create
      @user = Admin::User.find_by_email(account_params[:email])
      try_again and return unless @user
      try_again and return unless @user.authenticate(account_params[:password]) 
      try_again and return unless @user.admin?
      login!(@user)
    end

    def destroy
      logout!
    end

    protected

    def try_again
      @user = Admin::User.new(account_params)
      @user.errors.add(:base, "Account not found.")
      render :new
    end

    def account_params
      params.require(:user).permit(:email, :password)
    end
  end
end

apps/admin/app/controllers/admin/panel_controller.rb
module Admin
  class PanelController < ::Admin::ApplicationController
    class << self
      def parent_prefixes
        out = super
        if @parent_panel
          out.unshift("admin/#{@parent_panel.tableize}")
        end
        out
      end

      def parent_panel(parent)
        @parent_panel = parent.to_s.singularize
        prepend_before_filter :load_parent_object
      end
    end

    protected

    def parent_panel
      self.class.instance_variable_get("@parent_panel")
    end

    def parent_panel_class
      return nil unless parent_panel
      "Admin::#{parent_panel.classify}".constantize
    end

    def load_parent_object
      return unless parent_panel
      parent_obj = parent_panel_class.find(params["#{parent_panel}_id"])
      @parent = parent_obj
      instance_variable_set("@#{parent_panel}", @parent)
      @parent
    end
  end
end

apps/admin/app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < ::Admin::PanelController
    prepend_before_filter :fetch_object

    def show

    end

    def edit

    end

    def update
      if @post.update_attributes(object_params)
        redirect_to @post
      else
        flash[:alert] = @post.errors.full_messages.join(',')
        render :edit
      end
    end

    protected

    def fetch_object
      @post ||= Admin::Post.find(params[:id])
    end

    def object_params
      params.require(:post).permit!
    end
  end
end

apps/admin/app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ::Admin::PanelController
    prepend_before_filter :fetch_object

    def show

    end

    def posts
      @posts = Admin::Post.where(user_id: @user.id).page(params[:page])
    end

    def edit

    end

    def update
      if @user.update_attributes(object_params)
        redirect_to @user
      else
        flash[:alert] = @user.errors.full_messages.join(',')
        render :edit
      end
    end

    protected

    def fetch_object
      @user ||= Admin::User.find(params[:id])
    end

    def object_params
      params.require(:user).permit!
    end
  end
end

apps/admin/app/helpers/admin/application_helper.rb
module Admin
  module ApplicationHelper
    def display_time(time, format=:day_zone)
      return "" if time.nil?
      I18n.l(time, :format => "%Y-%m-%d %H:%M %Z")
    end

    def display_markdown(content)
      return "" if content.blank?
      markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
      markdown.render(content).html_safe
    end

    def display_property(name, value, opts = {})
      opts = opts.reverse_merge({
        :html_escape => true,
      })

      return "" if (value.is_a?(Fixnum) && value == 0 && !opts[:allow_zero]) || (value.blank? && value != false && !opts[:allow_blank])

      if value.is_a?(ActiveRecord::Base)
        case value.class.table_name.to_s
        when "users"
          opts[:formatter] ||= :link_to_name
        end
      end

      value = value.strftime("%Y-%m-%d %H:%M") if value.respond_to?(:strftime)
      if opts[:html_escape]
        value = h(value) if value.is_a?(String)
        name = h(name)
      end

      value = self.send(opts[:formatter], value) if opts[:formatter]
      value = simple_format(value.html_safe) if opts[:paragraphs]

      "<dt>#{name}</dt><dd class='value-#{name.to_s.downcase.gsub(/\W/,"-")}'>#{value}</dd>".html_safe
    end

    def display_properties(obj, *keys)
      return nil if obj.nil?
      options = keys.extract_options!

      out = []
      keys.each do |key|
        name = key.to_s.titleize
        method = key
        value = obj.send(method)
        if value.is_a?(Hash)
          value.each do |hk, hv|
            out << display_property(hk, hv, options)
          end
        else
          out << display_property(name, value, options)
        end
      end
      out.join("\n").html_safe
    end

    def display_name(user, limit = nil)
      return "" unless user
      user.extend(::Shared::User::Display) unless user.respond_to?(:full_name)
      name = user.full_name
      name = truncate(name, length: limit) if limit
      name
    end

    def link_to_name(user, limit = nil)
      return "" unless user
      link_to display_name(user, limit), user_path(user.id)
    end

    def render_rescue(name, *args)
      name = "index_#{name}" if panel_collection?
      render name.to_s, *args
    rescue ActionView::MissingTemplate
      ""
    end

    def skip_sidebar?
      @skip_panels || @skip_sidebar
    end

    def skip_header?
      @skip_panels
    end

    def skip_top_bottom?
      @skip_panels
    end

    def panel_collection?
      @panel_collection
    end

    def skip_panels
      @skip_panels = true
    end

    def panel_collection(options = {})
      @panel_collection = true
      skip_sidebar unless options[:sidebar]
    end

    def alert_bootstrap(rails)
      case rails.to_s
      when "notice"
        "success"
      when "error", "alert"
        "danger"
      else
        # other: "warning"
        "info"
      end
    end
  end
end

apps/admin/app/views/admin/home/index.haml
.row
  .col-md-6
    = form_for @post_search, url: post_search_path, method: 'get', html: {class: 'form-inline'} do |f|
      %fieldset
        %legend Post Search
        .form-group
          = f.text_field :query, placeholder: "content, post id", name: 'query', class: "form-control", style: "width: 300px;"
        = f.submit 'Post Search', class: "btn btn-default"

  .col-md-6
    = form_for @user_search, url: user_search_path, method: 'get', html: {class: 'form-inline'} do |f|
      %fieldset
        %legend User Search
        .form-group
          = f.text_field :query, placeholder: "email, name, user id", name: 'query', class: "form-control", style: "width: 300px;"
        = f.submit 'User Search', class: "btn btn-default"

apps/admin/app/views/admin/home/post_search.haml
%table.table
  %thead
    %tr
      %th Created At
      %th Poster
      %th Content
  %tbody
    - @results.each do |post|
      %tr
        %td= link_to(display_time(post.created_at), post_path(post))
        %td= link_to_name(post.user)
        %td= truncate(post.content, length: 120)

apps/admin/app/views/admin/home/user_search.haml
%table.table
  %thead
    %tr
      %th Created At
      %th Name
      %th Email
  %tbody
    - @results.each do |user|
      %tr
        %td= display_time(user.created_at)
        %td= link_to_name(user)
        %td= link_to user.email, user

apps/admin/app/views/admin/layouts/admin.haml
!!! 5
%html
  %head
    %meta{charset: 'utf-8'}
    %meta{'http-equiv' => 'X-UA-Compatible', content: 'IE=edge,chrome=1'}
    %meta{name: 'viewport',    content: 'width=device-width, initial-scale=1.0, maximum-scale=1.0 user-scalable=no'}
    %meta{name: 'apple-mobile-web-app-capable',          content: 'yes'}
    %meta{name: 'apple-mobile-web-app-status-bar-style', content: 'black'}

    %title TaskRabbit Admin

    = stylesheet_link_tag 'admin/manifests/application'
    = render_manifests('css')

    = yield :javascript

    = csrf_meta_tags

  %body
    .navbar.navbar-fixed-top.navbar-inverse{role: "navigation"}
      .container
        .navbar-header
          %a.navbar-brand{href: root_path} TaskRabbit Admin
        - if current_user
          %ul.nav.navbar-nav.navbar-right
            %li
              %a{href: logout_path} Logout


    .container
      - if !skip_header? && (header = render_rescue(:header)).present?
        #header.page-header
          = header

      - flash.keys.each do |name|
        %div{class: "alert alert-#{alert_bootstrap(name)}"}
          = flash[name] if flash[name].present?
        - flash.delete(name)

      .row
        - unless skip_sidebar?
          .col-md-3
            - if (title = render_rescue(:title)).present?
              #title.well
                = title

            - if (actions = render_rescue(:actions)).present?
              #actions.well
                = actions

            - if (panels = render_rescue(:panels)).present?
              #panels.well{role: "navigation"}
                = panels
        - col_class = skip_sidebar? ? "" : "col-md-9"
        %div{class: col_class}
          .container
            - if !skip_top_bottom? && (main_head = render_rescue(:top)).present?
              #top.row
                = main_head

            #panel.row
              = yield

            - if !skip_top_bottom? &&  (main_bottom = render_rescue(:bottom)).present?
              #bottom.row
                = main_bottom

      %footer

    = javascript_include_tag 'admin/manifests/application'
    = render_manifests('js')

apps/admin/app/views/admin/login/new.haml
%h1 Log In

= show_object_errors(@user)

= form_for @user, url: login_path do |f|
  .form-group
    = f.label :email
    = f.text_field :email, class: 'form-control'

  .form-group
    = f.label :password
    = f.password_field :password, class: 'form-control'

  = f.submit "Log In", class: "btn btn-primary"

apps/admin/app/views/admin/posts/_panels.haml
%ul.nav
  %li= link_to("Post", post_path(@post))
  %li= link_to("Edit", edit_post_path(@post))
  

apps/admin/app/views/admin/posts/edit.haml
%h2 Edit Post

= form_for @post do |f|
  .form-group
    = f.text_area :content, class: 'form-control'

  = f.submit "Post", class: "btn btn-primary"

apps/admin/app/views/admin/posts/show.haml
%h2 Post

%dl.dl-horizontal
  = display_properties(@post, :user, :created_at)

%hr

= display_markdown(@post.content)

apps/admin/app/views/admin/users/_header.haml
%h1=display_name(@user)

apps/admin/app/views/admin/users/_panels.haml
%ul.nav
  %li= link_to("Account", user_path(@user))
  %li= link_to("Edit", edit_user_path(@user))
  %li= link_to("Posts", posts_user_path(@user))

apps/admin/app/views/admin/users/edit.haml
%h2 Edit

= form_for @user do |f|
  .form-group
    = f.label :first_name
    = f.text_field :first_name, class: 'form-control'

  .form-group
    = f.label :last_name
    = f.text_field :last_name, class: 'form-control'

  .form-group
    = f.label :email
    = f.text_field :email, class: 'form-control'

  = f.submit "Edit", class: "btn btn-primary"

apps/admin/app/views/admin/users/posts.haml
%h2 My Posts

%table.table
  %thead
    %tr
      %th Time
      %th Content
  %tbody
    - @posts.each do |post|
      %tr
        %td= link_to(display_time(post.created_at), post_path(post))
        %td= display_markdown(post.content)

= paginate(@posts)

apps/admin/app/views/admin/users/show.haml
%h2 Info

%dl.dl-horizontal
  = display_properties(@user, :id, :email, :first_name, :last_name, :admin, :created_at)